### PR TITLE
Various memory optimizations

### PR DESCRIPTION
**Pull request by hack3ric**
See each commit message for details.

These are a lot of breaking changes, so please take your time to check if they are properly done :)

### CODE REVIEW

**Comment by hack3ric** [comment]
Oops, this failed to build on Rust <1.79 because the compiler cannot decide if `[Expression]: ToOwned`:

```
error[E0277]: the trait bound `[SetItem]: ToOwned` is not satisfied in `Expression`
   --> src/stmt.rs:245:14
    |
245 |     pub dev: Option<Expression>,
    |              ^^^^^^^^^^^^^^^^^^ within `Expression`, the trait `ToOwned` is not implemented for `[SetItem]`, which is required by `Expression: Sized`
    |
    = help: the trait `ToOwned` is implemented for `[T]`
note: required because it appears within the type `Expression`
   --> src/expr.rs:10:10
    |
10  | pub enum Expression {
    |          ^^^^^^^^^^
note: required by an implicit `Sized` bound in `std::option::Option`
   --> /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/option.rs:572:1

...and many, many similar errors
```

If bump MSRV to version this recent is not acceptable, keeping `Vec`s would probably fix this issue.

**Comment by hack3ric** [comment]
Fixed MSRV build and clippy. Please have another look :)

**Comment by jwhb** [comment]
Amazing @hack3ric!

Please allow us some more days to review it.

File: tests/json_tests.rs [hunk 1]
```diff
@@ -53,57 +54,57 @@ fn test_flowtable() {
...
-            }))),
-            NfObject::ListObject(Box::new(NfListObject::Rule(Rule {
+            })),
+            NfObject::ListObject(NfListObject::Rule(Rule {
                 family: NfFamily::INet,
-                table: "some_inet_table".to_string(),
-                chain: "some_inet_chain".to_string(),
-                expr: vec![
+                table: Cow::Borrowed("some_inet_table"),
+                chain: Cow::Borrowed("some_inet_chain"),
```
Comment (JKRhb) [inline tests/json_tests.rs:87]: Would it also be possible to use `.into()` in places like these?

**Review by JKRhb — COMMENTED** [review]
Thank you, @hack3ric, these changes look very good to me :) As I am personally not that familiar with `Cow`, see only one question regarding its usage in the tests below.

File: tests/json_tests.rs (hunk 1 above)
Comment (hack3ric) [reply tests/json_tests.rs:87]: `impl<'a> From<&'a str> for Cow<'a, str>` (and its fellows) is not `const` for now so `.into()` will result in a temporary value (as seen by rustc), so the resulting container is not `'static`, therefore cannot be borrowed `'static`. In this example both the outer slice and the inner `str` needs to be borrowed `'static`, leading to the following error:

```
error[E0716]: temporary value dropped while borrowed
   --> tests/json_tests.rs:57:33
    |
57  |            objects: Cow::Borrowed(&[
    |   ________________________________-^
    |  |_________________________________|
58  | ||             NfObject::ListObject(NfListObject::Table(Table {
59  | ||                 family: NfFamily::INet,
60  | ||                 name: Cow::Borrowed("some_inet_table"),
...   ||
106 | ||             })),
107 | ||         ]),
    | ||         ^
    | ||_________|
    |  |_________creates a temporary value which is freed while still in use
    |            cast requires that borrow lasts for `'static`
108 |        };
    |         - temporary value is freed at the end of this statement
```

If all of the outer containers are `Cow::Owned`, we can use `.into()` inside. Otherwise we probably need to stick to manually use `Cow::Borrowed`. I've also pushed a commit that allows temporary arrays to be used by replacing `'static` with `'a`. It will then just need to move the array in `Cow::Borrowed(&[..])` to another local variable to allow the usage of `.into()`:

```rust
let objects = [
    NfObject::ListObject(NfListObject::Table(Table {
        family: NfFamily::INet,
        name: "some_inet_table".into(), // here
        handle: None,
    })),
    // ...
];
let expected = Nftables {
    objects: objects.into(); // and here
};
```

**Comment by hack3ric** [comment]
Added one commit that lifts `'static` restriction on borrowed values, but added a lot of lifetimes, and updated examples in README as well.

**Comment by hack3ric** [comment]
Clippy issue should be fixed now.

**Comment by hack3ric** [comment]
FYI I have another patch ready for upstream, but it depends on this PR: https://github.com/namib-project/nftables-rs/commit/52902cd79b44b2582cb57beb4c137be66660a7ba. I will submit another PR after this and I hope this too can get into v0.6.0 too :)

**Comment by jwhb** [comment]
I performed a trivial memory benchmark of current `main` versus `main` + your PR.

<details>
<summary>main branch</summary>

```
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.05s
------------
 Nextest run ID f1af134f-590a-4b95-8e79-b4d43b409ebe with nextest profile: default
    Starting 11 tests across 1 binary
        PASS [   0.027s] nftables::deserialize test_deserialize_json_files::basic.json
        PASS [   0.032s] nftables::deserialize test_deserialize_json_files::counter.json
        PASS [   0.042s] nftables::deserialize test_deserialize_json_files::nftables-init.json
        PASS [   0.045s] nftables::deserialize test_deserialize_json_files::space-keys.json
        PASS [   0.052s] nftables::deserialize test_deserialize_json_files::flow.json
        PASS [   0.057s] nftables::deserialize test_deserialize_json_files::tproxy.json
        PASS [   0.065s] nftables::deserialize test_deserialize_json_files::nat.json
        PASS [   0.072s] nftables::deserialize test_deserialize_json_files::workstation_combined.json
        PASS [   0.080s] nftables::deserialize test_deserialize_json_files::synproxy.json
        PASS [   0.086s] nftables::deserialize test_deserialize_json_files::setmap.json
        PASS [   0.092s] nftables::deserialize test_deserialize_json_files::workstation.json
------------
     Summary [   0.095s] 11 tests run: 11 passed, 0 skipped
        PASS [   0.027s] nftables::deserialize test_deserialize_json_files::basic.json

--- STDOUT:              nftables::deserialize test_deserialize_json_files::basic.json ---

running 1 test
Deserializing file: resources/test/json/basic.json
Current physical memory usage: -20480
Current virtual memory usage: -4096
test test_deserialize_json_files::basic.json ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


        PASS [   0.032s] nftables::deserialize test_deserialize_json_files::counter.json

--- STDOUT:              nftables::deserialize test_deserialize_json_files::counter.json ---

running 1 test
Deserializing file: resources/test/json/counter.json
Current physical memory usage: -16384
Current virtual memory usage: -4096
test test_deserialize_json_files::counter.json ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


        PASS [   0.052s] nftables::deserialize test_deserialize_json_files::flow.json

--- STDOUT:              nftables::deserialize test_deserialize_json_files::flow.json ---

running 1 test
Deserializing file: resources/test/json/flow.json
Current physical memory usage: -16384
Current virtual memory usage: -4096
test test_deserialize_json_files::flow.json ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


        PASS [   0.065s] nftables::deserialize test_deserialize_json_files::nat.json

--- STDOUT:              nftables::deserialize test_deserialize_json_files::nat.json ---

running 1 test
Deserializing file: resources/test/json/nat.json
Current physical memory usage: -20480
Current virtual memory usage: -4096
test test_deserialize_json_files::nat.json ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


        PASS [   0.042s] nftables::deserialize test_deserialize_json_files::nftables-init.json

--- STDOUT:              nftables::deserialize test_deserialize_json_files::nftables-init.json ---

running 1 test
Deserializing file: resources/test/json/nftables-init.json
Current physical memory usage: -24576
Current virtual memory usage: -8192
test test_deserialize_json_files::nftables-init.json ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s


        PASS [   0.086s] nftables::deserialize test_deserialize_json_files::setmap.json

--- STDOUT:              nftables::deserialize test_deserialize_json_files::setmap.json ---

running 1 test
Deserializing file: resources/test/json/setmap.json
Current physical memory usage: -16384
Current virtual memory usage: -4096
test test_deserialize_json_files::setmap.json ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


        PASS [   0.045s] nftables::deserialize test_deserialize_json_files::space-keys.json

--- STDOUT:              nftables::deserialize test_deserialize_json_files::space-keys.json ---

running 1 test
Deserializing file: resources/test/json/space-keys.json
Current physical memory usage: -24576
Current virtual memory usage: -8192
test test_deserialize_json_files::space-keys.json ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


        PASS [   0.080s] nftables::deserialize test_deserialize_json_files::synproxy.json

--- STDOUT:              nftables::deserialize test_deserialize_json_files::synproxy.json ---

running 1 test
Deserializing file: resources/test/json/synproxy.json
Current physical memory usage: -20480
Current virtual memory usage: -4096
test test_deserialize_json_files::synproxy.json ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


        PASS [   0.057s] nftables::deserialize test_deserialize_json_files::tproxy.json

--- STDOUT:              nftables::deserialize test_deserialize_json_files::tproxy.json ---

running 1 test
Deserializing file: resources/test/json/tproxy.json
Current physical memory usage: -16384
Current virtual memory usage: -4096
test test_deserialize_json_files::tproxy.json ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


        PASS [   0.092s] nftables::deserialize test_deserialize_json_files::workstation.json

--- STDOUT:              nftables::deserialize test_deserialize_json_files::workstation.json ---

running 1 test
Deserializing file: resources/test/json/workstation.json
Current physical memory usage: -16384
Current virtual memory usage: -4096
test test_deserialize_json_files::workstation.json ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


        PASS [   0.072s] nftables::deserialize test_deserialize_json_files::workstation_combined.json

--- STDOUT:              nftables::deserialize test_deserialize_json_files::workstation_combined.json ---

running 1 test
Deserializing file: resources/test/json/workstation_combined.json
Current physical memory usage: -20480
Current virtual memory usage: -4096
test test_deserialize_json_files::workstation_combined.json ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

</details>


<details>
<summary>cow branch</summary>

```
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.04s
------------
 Nextest run ID 09889313-078e-450e-bf34-cc2685fe0a80 with nextest profile: default
    Starting 11 tests across 1 binary
        PASS [   0.028s] nftables::deserialize test_deserialize_json_files::basic.json
        PASS [   0.036s] nftables::deserialize test_deserialize_json_files::nftables-init.json
        PASS [   0.039s] nftables::deserialize test_deserialize_json_files::setmap.json
        PASS [   0.045s] nftables::deserialize test_deserialize_json_files::tproxy.json
        PASS [   0.054s] nftables::deserialize test_deserialize_json_files::flow.json
        PASS [   0.061s] nftables::deserialize test_deserialize_json_files::space-keys.json
        PASS [   0.067s] nftables::deserialize test_deserialize_json_files::workstation_combined.json
        PASS [   0.075s] nftables::deserialize test_deserialize_json_files::counter.json
        PASS [   0.081s] nftables::deserialize test_deserialize_json_files::synproxy.json
        PASS [   0.088s] nftables::deserialize test_deserialize_json_files::workstation.json
        PASS [   0.095s] nftables::deserialize test_deserialize_json_files::nat.json
------------
     Summary [   0.096s] 11 tests run: 11 passed, 0 skipped
        PASS [   0.028s] nftables::deserialize test_deserialize_json_files::basic.json

--- STDOUT:              nftables::deserialize test_deserialize_json_files::basic.json ---

running 1 test
Deserializing file: resources/test/json/basic.json
Current physical memory usage: -12288
Current virtual memory usage: -4096
test test_deserialize_json_files::basic.json ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


        PASS [   0.075s] nftables::deserialize test_deserialize_json_files::counter.json

--- STDOUT:              nftables::deserialize test_deserialize_json_files::counter.json ---

running 1 test
Deserializing file: resources/test/json/counter.json
Current physical memory usage: -16384
Current virtual memory usage: -4096
test test_deserialize_json_files::counter.json ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


        PASS [   0.054s] nftables::deserialize test_deserialize_json_files::flow.json

--- STDOUT:              nftables::deserialize test_deserialize_json_files::flow.json ---

running 1 test
Deserializing file: resources/test/json/flow.json
Current physical memory usage: -12288
Current virtual memory usage: -4096
test test_deserialize_json_files::flow.json ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


        PASS [   0.095s] nftables::deserialize test_deserialize_json_files::nat.json

--- STDOUT:              nftables::deserialize test_deserialize_json_files::nat.json ---

running 1 test
Deserializing file: resources/test/json/nat.json
Current physical memory usage: -12288
Current virtual memory usage: -4096
test test_deserialize_json_files::nat.json ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


        PASS [   0.036s] nftables::deserialize test_deserialize_json_files::nftables-init.json

--- STDOUT:              nftables::deserialize test_deserialize_json_files::nftables-init.json ---

running 1 test
Deserializing file: resources/test/json/nftables-init.json
Current physical memory usage: -24576
Current virtual memory usage: -8192
test test_deserialize_json_files::nftables-init.json ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s


        PASS [   0.039s] nftables::deserialize test_deserialize_json_files::setmap.json

--- STDOUT:              nftables::deserialize test_deserialize_json_files::setmap.json ---

running 1 test
Deserializing file: resources/test/json/setmap.json
Current physical memory usage: -16384
Current virtual memory usage: -4096
test test_deserialize_json_files::setmap.json ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


        PASS [   0.061s] nftables::deserialize test_deserialize_json_files::space-keys.json

--- STDOUT:              nftables::deserialize test_deserialize_json_files::space-keys.json ---

running 1 test
Deserializing file: resources/test/json/space-keys.json
Current physical memory usage: -20480
Current virtual memory usage: -8192
test test_deserialize_json_files::space-keys.json ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


        PASS [   0.081s] nftables::deserialize test_deserialize_json_files::synproxy.json

--- STDOUT:              nftables::deserialize test_deserialize_json_files::synproxy.json ---

running 1 test
Deserializing file: resources/test/json/synproxy.json
Current physical memory usage: -20480
Current virtual memory usage: -4096
test test_deserialize_json_files::synproxy.json ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


        PASS [   0.045s] nftables::deserialize test_deserialize_json_files::tproxy.json

--- STDOUT:              nftables::deserialize test_deserialize_json_files::tproxy.json ---

running 1 test
Deserializing file: resources/test/json/tproxy.json
Current physical memory usage: -12288
Current virtual memory usage: -4096
test test_deserialize_json_files::tproxy.json ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


        PASS [   0.088s] nftables::deserialize test_deserialize_json_files::workstation.json

--- STDOUT:              nftables::deserialize test_deserialize_json_files::workstation.json ---

running 1 test
Deserializing file: resources/test/json/workstation.json
Current physical memory usage: -16384
Current virtual memory usage: -4096
test test_deserialize_json_files::workstation.json ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


        PASS [   0.067s] nftables::deserialize test_deserialize_json_files::workstation_combined.json

--- STDOUT:              nftables::deserialize test_deserialize_json_files::workstation_combined.json ---

running 1 test
Deserializing file: resources/test/json/workstation_combined.json
Current physical memory usage: -16384
Current virtual memory usage: -4096
test test_deserialize_json_files::workstation_combined.json ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

</details>

<details>

</details>

File: src/schema.rs [hunk 2]
```diff
@@ -560,17 +560,17 @@ pub struct FlowTable {
     /// The *devices* are specified as iifname(s) of the input interface(s) of the traffic that should be offloaded.
     ///
     /// Devices are required for both traffic directions.
-    /// Vec of device names, e.g. `vec!["wg0".to_string(), "wg0".to_string()]`.
-    pub dev: Option<Vec<String>>,
+    /// Cow slice of device names, e.g. `vec!["wg0".into(), "wg1".into()].into()`.
```
Comment (jwhb) [inline src/schema.rs:563]: nice!

**Review by jwhb — APPROVED** [review]

File: src/schema.rs (hunk 2 above)
Comment (jwhb) [reply src/schema.rs:563]: I am afraid of the impact of the breaking changes for users of this crate, but this is obviously the way forward.

**Review by JKRhb — APPROVED** [review]
Thank you, @hack3ric!
